# swaynag
complete -c swaynag -s C -l config --description 'The config file to use. Default: $HOME/.swaylock/config, $XDG_CONFIG_HOME/swaylock/config, and SYSCONFDIR/swaylock/config.'
complete -c swaynag -s d -l debug --description 'Enable debugging.'
complete -c swaynag -s e -l edge --description 'Set the edge to use: top or bottom'
complete -c swaynag -s f -l font --description 'Set the font to use.'
complete -c swaynag -s h -l help --description 'Show help message and quit.'
complete -c swaynag -s b -l button --description 'Create a button with a text and an action which is executed when pressed. Multiple buttons can be defined by providing the flag multiple times.'
complete -c swaynag -s l -l detailed-message --description 'Read a detailed message from stdin. A button to toggle details will be added. Details are shown in a scrollable multi-line text area.'
complete -c swaynag -s L -l detailed-button --description 'Set the text for the button that toggles details. This has no effect if there is not a detailed message. The default is "Toggle details".'
complete -c swaynag -s m -l message --description 'Set the message text.'
complete -c swaynag -s o -l output --description 'Set the output to use.'
complete -c swaynag -s s -l dismiss-button --description 'Sets the text for the dismiss nagbar button. The default is "X".'
complete -c swaynag -s t -l type --description 'Set the message type. Two types are created by default "error" and "warning". Custom types can be defined in the config file.'
complete -c swaynag -s v -l version --description 'Show the version number and quit.'

# Appearance
complete -c swaynag -l background --description 'Set the color of the background.'
complete -c swaynag -l border --description 'Set the color of the border.'
complete -c swaynag -l border-bottom --description 'Set the color of the bottom border.'
complete -c swaynag -l button-background --description 'Set the color for the background for buttons.'
complete -c swaynag -l text --description 'Set the text color.'
complete -c swaynag -l border-bottom-size --description 'Set the thickness of the bottom border.'
complete -c swaynag -l message-padding --description 'Set the padding for the message.'
complete -c swaynag -l details-border-size --description 'Set the thickness for the details border.'
complete -c swaynag -l button-border-size --description 'Set the thickness for the button border.'
complete -c swaynag -l button-gap --description 'Set the size of the gap between buttons.'
complete -c swaynag -l button-dismiss-gap --description 'Set the size of the gap between the dismiss button and another button.'
complete -c swaynag -l button-margin-right --description 'Set the margin from the right of the dismiss button to edge.'
complete -c swaynag -l button-padding --description 'Set the padding for the button text.'
